version: "3.9"
services:
  nova:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ["python", "nova.py", "start"]
    volumes:
      - ..:/app
    ports:
      - "9800:9800"
      - "9700:9700"
