"""Runtime-safe integration catalog exposed to the API and UI."""

from __future__ import annotations

INTEGRATION_SCHEMAS = {
    "gmail": {
        "name": "Gmail",
        "icon": "gmail",
        "category": "Communication",
        "description": "Search sent and received emails. Detect duplicates and verify prior contact history.",
        "credentials": [
            {
                "key": "gmail_token",
                "label": "OAuth Token (JSON)",
                "type": "textarea",
                "required": True,
                "hint": "Paste the JSON from the Google OAuth flow",
            },
        ],
        "capabilities": ["gmail_search", "contact_check"],
        "setup_url": "https://console.cloud.google.com/apis/credentials",
    },
    "slack": {
        "name": "Slack",
        "icon": "slack",
        "category": "Communication",
        "description": "Search messages, verify channels, and send notifications.",
        "credentials": [
            {
                "key": "slack_token",
                "label": "Bot Token",
                "type": "password",
                "required": True,
                "hint": "xoxb-... from Slack App settings",
            },
        ],
        "capabilities": ["slack_search", "slack_post"],
        "setup_url": "https://api.slack.com/apps",
    },
    "discord": {
        "name": "Discord",
        "icon": "discord",
        "category": "Communication",
        "description": "Send messages and read channel history for governance context.",
        "credentials": [
            {
                "key": "discord_token",
                "label": "Bot Token",
                "type": "password",
                "required": True,
                "hint": "From Discord Developer Portal",
            },
        ],
        "capabilities": ["discord_send", "discord_read"],
        "setup_url": "https://discord.com/developers/applications",
    },
    "telegram": {
        "name": "Telegram",
        "icon": "telegram",
        "category": "Communication",
        "description": "Send alerts and notifications through a Telegram bot.",
        "credentials": [
            {
                "key": "telegram_token",
                "label": "Bot Token",
                "type": "password",
                "required": True,
                "hint": "From @BotFather on Telegram",
            },
        ],
        "capabilities": ["telegram_send"],
        "setup_url": "https://core.telegram.org/bots#botfather",
    },
    "notion": {
        "name": "Notion",
        "icon": "notion",
        "category": "Productivity",
        "description": "Query Notion databases as a source of truth for validations.",
        "credentials": [
            {
                "key": "notion_token",
                "label": "Integration Token",
                "type": "password",
                "required": True,
                "hint": "From notion.so/my-integrations",
            },
            {
                "key": "database_id",
                "label": "Default Database ID",
                "type": "text",
                "required": False,
            },
        ],
        "capabilities": ["notion_search"],
        "setup_url": "https://www.notion.so/my-integrations",
    },
    "linear": {
        "name": "Linear",
        "icon": "linear",
        "category": "Development",
        "description": "Search issues, create tickets, and check sprint status.",
        "credentials": [
            {
                "key": "linear_token",
                "label": "API Key",
                "type": "password",
                "required": True,
                "hint": "From Linear Settings > API",
            },
        ],
        "capabilities": ["linear_search", "linear_create"],
        "setup_url": "https://linear.app/settings/api",
    },
    "jira": {
        "name": "Jira",
        "icon": "jira",
        "category": "Development",
        "description": "Search tickets and verify blockers before deployment.",
        "credentials": [
            {
                "key": "jira_url",
                "label": "Instance URL",
                "type": "text",
                "required": True,
                "hint": "https://your-org.atlassian.net",
            },
            {
                "key": "jira_user",
                "label": "Email",
                "type": "text",
                "required": True,
            },
            {
                "key": "jira_token",
                "label": "API Token",
                "type": "password",
                "required": True,
                "hint": "From Atlassian API token settings",
            },
        ],
        "capabilities": ["jira_search", "jira_create"],
        "setup_url": "https://id.atlassian.com/manage-profile/security/api-tokens",
    },
    "hubspot": {
        "name": "HubSpot",
        "icon": "hubspot",
        "category": "CRM",
        "description": "Verify contacts, check deals, and prevent duplicate outreach.",
        "credentials": [
            {
                "key": "hubspot_token",
                "label": "Private App Token",
                "type": "password",
                "required": True,
            },
        ],
        "capabilities": ["contact_check", "deal_check"],
        "setup_url": "https://developers.hubspot.com/docs/api/private-apps",
    },
    "salesforce": {
        "name": "Salesforce",
        "icon": "salesforce",
        "category": "CRM",
        "description": "Run SOQL queries against Leads, Contacts, and Opportunities.",
        "credentials": [
            {
                "key": "salesforce_instance",
                "label": "Instance URL",
                "type": "text",
                "required": True,
                "hint": "https://your-org.salesforce.com",
            },
            {
                "key": "salesforce_token",
                "label": "Access Token",
                "type": "password",
                "required": True,
            },
        ],
        "capabilities": ["salesforce_query"],
        "setup_url": "https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/",
    },
    "github": {
        "name": "GitHub",
        "icon": "github",
        "category": "Development",
        "description": "Check open issues and PRs, and block deploys if critical bugs exist.",
        "credentials": [
            {
                "key": "github_token",
                "label": "Personal Access Token",
                "type": "password",
                "required": True,
                "hint": "ghp_... from GitHub Settings",
            },
            {
                "key": "github_repo",
                "label": "Default Repo (owner/repo)",
                "type": "text",
                "required": False,
            },
        ],
        "capabilities": ["github_search", "github_pr_check"],
        "setup_url": "https://github.com/settings/tokens",
    },
    "stripe": {
        "name": "Stripe",
        "icon": "stripe",
        "category": "Payments",
        "description": "Verify charges, check fraud signals, and enforce payment limits.",
        "credentials": [
            {
                "key": "stripe_secret_key",
                "label": "Secret Key",
                "type": "password",
                "required": True,
                "hint": "sk_live_... or sk_test_...",
            },
            {
                "key": "stripe_charge_limit",
                "label": "Max Charge (cents)",
                "type": "text",
                "required": False,
                "hint": "Default: 50000 ($500)",
            },
        ],
        "capabilities": ["payment_check", "customer_check"],
        "setup_url": "https://dashboard.stripe.com/apikeys",
    },
    "airtable": {
        "name": "Airtable",
        "icon": "airtable",
        "category": "Data",
        "description": "Query Airtable bases for duplicate detection and record verification.",
        "credentials": [
            {
                "key": "airtable_token",
                "label": "Personal Access Token",
                "type": "password",
                "required": True,
            },
            {
                "key": "airtable_base_id",
                "label": "Base ID",
                "type": "text",
                "required": False,
            },
        ],
        "capabilities": ["airtable_search"],
        "setup_url": "https://airtable.com/create/tokens",
    },
    "supabase": {
        "name": "Supabase",
        "icon": "supabase",
        "category": "Database",
        "description": "Query Postgres through the Supabase REST API.",
        "credentials": [
            {
                "key": "supabase_url",
                "label": "Project URL",
                "type": "text",
                "required": True,
            },
            {
                "key": "supabase_service_key",
                "label": "Service Role Key",
                "type": "password",
                "required": True,
            },
        ],
        "capabilities": ["db_query"],
        "setup_url": "https://app.supabase.com/project/_/settings/api",
    },
    "postgres": {
        "name": "PostgreSQL",
        "icon": "postgres",
        "category": "Database",
        "description": "Run direct Postgres queries for deep validation logic.",
        "credentials": [
            {
                "key": "connection_string",
                "label": "Connection String",
                "type": "password",
                "required": True,
                "hint": "postgresql://user:pass@host:5432/db",
            },
        ],
        "capabilities": ["db_query"],
        "setup_url": "https://www.postgresql.org/docs/current/libpq-connect.html",
    },
    "redis": {
        "name": "Redis",
        "icon": "redis",
        "category": "Database",
        "description": "Handle rate limiting, deduplication, and fast key-value checks.",
        "credentials": [
            {
                "key": "redis_url",
                "label": "Redis URL",
                "type": "text",
                "required": False,
                "hint": "redis://localhost:6379",
            },
        ],
        "capabilities": ["rate_limit_check", "key_check"],
        "setup_url": "https://redis.io/docs/connect/",
    },
    "pagerduty": {
        "name": "PagerDuty",
        "icon": "pagerduty",
        "category": "Observability",
        "description": "Check active incidents and trigger alerts from Nova decisions.",
        "credentials": [
            {
                "key": "pagerduty_token",
                "label": "API Token",
                "type": "password",
                "required": True,
            },
            {
                "key": "pagerduty_routing_key",
                "label": "Events Routing Key",
                "type": "password",
                "required": False,
            },
        ],
        "capabilities": ["incident_check", "alert_trigger"],
        "setup_url": "https://developer.pagerduty.com/api-reference/",
    },
    "datadog": {
        "name": "Datadog",
        "icon": "datadog",
        "category": "Observability",
        "description": "Send events, check monitors, and correlate them with system health.",
        "credentials": [
            {
                "key": "datadog_api_key",
                "label": "API Key",
                "type": "password",
                "required": True,
            },
            {
                "key": "datadog_app_key",
                "label": "Application Key",
                "type": "password",
                "required": False,
            },
        ],
        "capabilities": ["monitor_check", "event_send"],
        "setup_url": "https://app.datadoghq.com/organization-settings/api-keys",
    },
    "webhook": {
        "name": "Custom Webhook / REST API",
        "icon": "webhook",
        "category": "Generic",
        "description": "Connect any REST API or webhook for custom verification.",
        "credentials": [
            {
                "key": "webhook_url",
                "label": "Default URL",
                "type": "text",
                "required": False,
            },
            {
                "key": "webhook_token",
                "label": "Bearer Token",
                "type": "password",
                "required": False,
            },
        ],
        "capabilities": ["http_check"],
        "setup_url": None,
    },
    "zapier": {
        "name": "Zapier",
        "icon": "zapier",
        "category": "Automation",
        "description": "Trigger any Zap when Nova makes a decision.",
        "credentials": [
            {
                "key": "zapier_webhook_url",
                "label": "Webhook URL",
                "type": "text",
                "required": True,
                "hint": "From Zapier > Webhooks by Zapier",
            },
        ],
        "capabilities": ["automation_trigger"],
        "setup_url": "https://zapier.com/apps/webhook/integrations",
    },
    "make": {
        "name": "Make (Integromat)",
        "icon": "make",
        "category": "Automation",
        "description": "Trigger Make scenarios from Nova decisions.",
        "credentials": [
            {
                "key": "make_webhook_url",
                "label": "Webhook URL",
                "type": "text",
                "required": True,
            },
        ],
        "capabilities": ["automation_trigger"],
        "setup_url": "https://www.make.com/en/help/tools/webhooks",
    },
    "whatsapp": {
        "name": "WhatsApp (Evolution API)",
        "icon": "whatsapp",
        "category": "Communication",
        "description": "Duplicate detection, conversation history, and message sending for Melissa workflows.",
        "credentials": [
            {
                "key": "evolution_url",
                "label": "Evolution API URL",
                "type": "text",
                "required": True,
                "hint": "http://localhost:8080 or your Evolution API server",
            },
            {
                "key": "evolution_key",
                "label": "API Key",
                "type": "password",
                "required": True,
                "hint": "Set in Evolution API config",
            },
            {
                "key": "evolution_instance",
                "label": "Instance Name",
                "type": "text",
                "required": True,
                "hint": "Your Evolution instance name, for example melissa",
            },
        ],
        "capabilities": ["duplicate_check", "history_read", "send_message"],
        "setup_url": "https://github.com/EvolutionAPI/evolution-api",
    },
}

