"""Known agent fingerprints used by the discovery scanner."""

from __future__ import annotations

from typing import Any


AGENT_FINGERPRINTS: dict[str, dict[str, Any]] = {
    "codex_cli": {
        "name": "Codex CLI",
        "type": "cli_agent",
        "icon": "terminal",
        "color": "#00D4AA",
        "logo_path": "/agent-logos/codex.svg",
        "detection": {
            "required_matches": 2,
            "config_paths": [
                "~/.codex",
                "~/.codex/config.toml",
                "~/.codex/config.json",
                "~/.codex/config.yaml",
                "~/.config/codex",
            ],
            "binary_names": ["codex"],
            "process_patterns": ["codex"],
            "npm_packages": ["@openai/codex"],
            "pip_packages": [],
            "env_vars": ["CODEX_API_KEY", "OPENAI_API_KEY"],
            "default_ports": [],
            "docker_images": [],
        },
        "capabilities": {
            "can_execute_code": True,
            "can_modify_files": True,
            "can_run_commands": True,
            "can_access_network": True,
            "has_api": False,
            "has_websocket": False,
            "communication": "cli_subprocess",
            "supported_models": ["o4-mini", "o3", "gpt-4.1"],
        },
        "risk_profile": {
            "base_risk": 45,
            "risk_factors": ["code_execution", "file_system_access", "shell_access"],
        },
        "integration": {
            "method": "subprocess_wrapper",
            "health_check": "codex --version",
        },
    },
    "n8n": {
        "name": "N8N Workflow Automation",
        "type": "workflow_engine",
        "icon": "workflow",
        "color": "#FF6D5A",
        "logo_path": "/agent-logos/n8n.svg",
        "detection": {
            "required_matches": 2,
            "config_paths": ["~/.n8n", "~/.n8n/config"],
            "binary_names": ["n8n"],
            "process_patterns": ["n8n", "node.*n8n"],
            "npm_packages": ["n8n"],
            "pip_packages": [],
            "env_vars": ["N8N_BASIC_AUTH_USER", "N8N_PORT", "N8N_HOST"],
            "default_ports": [5678, 5679],
            "docker_images": ["n8nio/n8n", "docker.n8n.io/n8nio/n8n"],
            "health_paths": ["/healthz", "/rest/healthz"],
        },
        "capabilities": {
            "can_execute_code": True,
            "can_modify_files": False,
            "can_run_commands": True,
            "can_access_network": True,
            "has_api": True,
            "has_websocket": True,
            "communication": "rest_api",
            "api_base": "http://localhost:5678/api/v1",
            "webhook_support": True,
            "supported_nodes": ["AI Agent", "OpenAI", "HTTP Request", "Code", "Function"],
        },
        "risk_profile": {
            "base_risk": 40,
            "risk_factors": ["workflow_execution", "external_api_calls", "data_transformation"],
        },
        "integration": {
            "method": "rest_api",
            "health_check": "GET /healthz",
            "auth_type": "basic_auth",
        },
    },
    "open_interpreter": {
        "name": "Open Interpreter",
        "type": "code_interpreter",
        "icon": "code",
        "color": "#111111",
        "logo_path": "/agent-logos/open-interpreter.svg",
        "detection": {
            "required_matches": 2,
            "config_paths": ["~/.config/open-interpreter", "~/.open-interpreter"],
            "binary_names": ["interpreter", "open-interpreter"],
            "process_patterns": ["interpreter", "open.interpreter"],
            "npm_packages": [],
            "pip_packages": ["open-interpreter"],
            "env_vars": [],
            "default_ports": [8000],
            "docker_images": ["openinterpreter/open-interpreter"],
            "health_paths": ["/health"],
        },
        "capabilities": {
            "can_execute_code": True,
            "can_modify_files": True,
            "can_run_commands": True,
            "can_access_network": True,
            "has_api": True,
            "has_websocket": False,
            "communication": "subprocess_or_api",
            "supported_languages": ["python", "javascript", "bash", "r"],
        },
        "risk_profile": {
            "base_risk": 65,
            "risk_factors": ["unrestricted_code_execution", "file_system_full_access", "shell_root"],
        },
        "integration": {
            "method": "python_import",
            "health_check": "interpreter --version",
            "python_module": "interpreter",
        },
    },
    "openclaw": {
        "name": "OpenClaw",
        "type": "ai_agent_framework",
        "icon": "claw",
        "color": "#7C3AED",
        "logo_path": "/agent-logos/openclaw.svg",
        "detection": {
            "required_matches": 2,
            "config_paths": ["~/.openclaw", "~/.config/openclaw"],
            "binary_names": ["openclaw"],
            "process_patterns": ["openclaw", "openclaw-gateway"],
            "npm_packages": [],
            "pip_packages": ["openclaw"],
            "env_vars": ["OPENCLAW_API_KEY"],
            "default_ports": [8080, 18789, 18791],
            "docker_images": ["openclaw"],
            "health_paths": ["/health", "/api/health"],
        },
        "capabilities": {
            "can_execute_code": True,
            "can_modify_files": True,
            "can_run_commands": True,
            "can_access_network": True,
            "has_api": True,
            "has_websocket": True,
            "communication": "rest_api_or_websocket",
        },
        "risk_profile": {
            "base_risk": 50,
            "risk_factors": ["autonomous_execution", "tool_usage"],
        },
        "integration": {
            "method": "rest_api",
            "health_check": "GET /health",
        },
    },
    "langchain_agent": {
        "name": "LangChain Agent",
        "type": "framework_agent",
        "icon": "chain",
        "color": "#1C3C3C",
        "logo_path": "/agent-logos/langchain.svg",
        "detection": {
            "required_matches": 2,
            "config_paths": [],
            "binary_names": ["langchain", "langserve"],
            "process_patterns": ["langchain", "langserve"],
            "npm_packages": ["langchain"],
            "pip_packages": ["langchain", "langchain-core", "langchain-community", "langgraph"],
            "env_vars": ["LANGCHAIN_API_KEY", "LANGCHAIN_TRACING_V2"],
            "default_ports": [8000, 8001],
            "docker_images": [],
            "health_paths": ["/health"],
        },
        "capabilities": {
            "can_execute_code": True,
            "can_modify_files": False,
            "can_run_commands": False,
            "can_access_network": True,
            "has_api": True,
            "has_websocket": False,
            "communication": "langserve_api",
        },
        "risk_profile": {
            "base_risk": 35,
            "risk_factors": ["tool_usage", "chain_execution"],
        },
        "integration": {
            "method": "langserve_or_import",
            "health_check": "GET /health",
        },
    },
    "crewai": {
        "name": "CrewAI",
        "type": "multi_agent_framework",
        "icon": "users",
        "color": "#FF4500",
        "logo_path": "/agent-logos/crewai.svg",
        "detection": {
            "required_matches": 2,
            "config_paths": [],
            "binary_names": ["crewai"],
            "process_patterns": ["crewai"],
            "npm_packages": [],
            "pip_packages": ["crewai"],
            "env_vars": [],
            "default_ports": [],
            "docker_images": [],
        },
        "capabilities": {
            "can_execute_code": True,
            "can_modify_files": True,
            "can_run_commands": True,
            "can_access_network": True,
            "has_api": False,
            "has_websocket": False,
            "communication": "python_import",
            "multi_agent": True,
        },
        "risk_profile": {
            "base_risk": 55,
            "risk_factors": ["multi_agent_coordination", "autonomous_task_execution"],
        },
        "integration": {
            "method": "python_wrapper",
            "python_module": "crewai",
        },
    },
    "autogen": {
        "name": "AutoGen",
        "type": "multi_agent_framework",
        "icon": "microsoft",
        "color": "#0078D4",
        "logo_path": "/agent-logos/autogen.svg",
        "detection": {
            "required_matches": 2,
            "config_paths": [],
            "binary_names": [],
            "process_patterns": ["autogen"],
            "npm_packages": [],
            "pip_packages": ["pyautogen", "autogen-agentchat"],
            "env_vars": [],
            "default_ports": [],
            "docker_images": [],
        },
        "capabilities": {
            "can_execute_code": True,
            "can_modify_files": True,
            "can_run_commands": True,
            "can_access_network": True,
            "has_api": False,
            "has_websocket": False,
            "communication": "python_import",
            "multi_agent": True,
        },
        "risk_profile": {
            "base_risk": 50,
            "risk_factors": ["multi_agent_conversation", "code_execution"],
        },
        "integration": {
            "method": "python_wrapper",
            "python_module": "autogen",
        },
    },
    "generic_docker_agent": {
        "name": "Docker Container Agent",
        "type": "containerized_agent",
        "icon": "container",
        "color": "#2496ED",
        "discoverable": False,
        "detection": {
            "docker_label_patterns": ["ai.agent", "nova.agent", "agent.type"],
            "docker_env_patterns": ["AGENT_", "AI_AGENT", "LLM_"],
        },
        "capabilities": {
            "has_api": True,
            "communication": "docker_api",
        },
        "risk_profile": {
            "base_risk": 30,
            "risk_factors": ["container_escape_potential"],
        },
        "integration": {
            "method": "docker_api",
            "health_check": "docker inspect --format={{.State.Health.Status}}",
        },
    },
    "generic_process_agent": {
        "name": "System Process Agent",
        "type": "process_agent",
        "icon": "cpu",
        "color": "#6B7280",
        "discoverable": False,
        "detection": {
            "process_keyword_patterns": [
                "agent",
                "bot",
                "assistant",
                "ai-worker",
                "llm-service",
                "inference",
                "completion",
            ],
        },
        "capabilities": {
            "communication": "signal_or_pipe",
        },
        "risk_profile": {
            "base_risk": 40,
            "risk_factors": ["unknown_process", "unverified"],
        },
        "integration": {
            "method": "process_monitor",
        },
    },
}
